spring:
  datasource:
    url: jdbc:mysql://192.168.1.128/learning
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
server:
  port: 8080
  servlet:
    context-path: /backstage_management
mybatis:
    mapper-locations: /mappering/*/*.xml
    type-aliases-package: com.jk.*.pojo














