spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver


  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

server:
  port: 8080
  servlet:
    context-path: /backstage_management














