spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1712b-alh
    username: root
    password: 999
    driver-class-name: com.mysql.jdbc.Driver


  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8080
  servlet:
    context-path: /backstage_management














